// Mocks generated by Mockito 5.4.4 from annotations
// in crypto_watcher/test/bloc/token/token_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:crypto_watcher/entity/Token.dart' as _i4;
import 'package:crypto_watcher/repository/token_repository.dart' as _i2;
import 'package:fl_chart/fl_chart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenRepository extends _i1.Mock implements _i2.TokenRepository {
  MockTokenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Token>> getTokenList() => (super.noSuchMethod(
        Invocation.method(
          #getTokenList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Token>>.value(<_i4.Token>[]),
      ) as _i3.Future<List<_i4.Token>>);

  @override
  _i3.Future<Map<String, dynamic>> getTokenDetails(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTokenDetails,
          [id],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i5.FlSpot>> fetchTokenPriceData(String? tokenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTokenPriceData,
          [tokenId],
        ),
        returnValue: _i3.Future<List<_i5.FlSpot>>.value(<_i5.FlSpot>[]),
      ) as _i3.Future<List<_i5.FlSpot>>);
}
